---
- name: CREATE NGINX DOCKER DIRECTORIES TASK
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - /opt/docker/docker-nginx/ssl
    - /opt/docker/docker-nginx/log
    - /opt/docker/docker-nginx/conf