- name: CREATE RSYNC BACKUP DIRECTORIES TASK
  file:
    path: '{{ item }}'
    state: directory
    mode: '0777'
  with_items:
    - /opt/RSYNC_BACKUP/BACKUP
    - /opt/RSYNC_BACKUP/WEB
    - /opt/RSYNC_MIRROR