---
- name: STOP POSTGRESQL TASK
  systemd:
    name: postgresql
    state: stopped

- name: CHANGE PG_HBA.CONF TASK
  blockinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    block: |
      host    replication     repl            10.10.10.61/32            md5
      host    replication     repl            10.10.10.62/32            md5
      host    replication     all             10.10.10.61/32            md5
      host    replication     all             10.10.10.62/32            md5

- name: START POSTGRESQL TASK
  systemd:
    name: postgresql
    state: started

- name: REPL REPL USER TASK
  become: true
  become_user: postgres
  postgresql_user:
    name: repl
    password: repl
    role_attr_flags: REPLICATION

- name: CREATE SLOT TASK
  become: true
  become_user: postgres
  postgresql_slot:
    slot_name: pg_slot_1
    db: postgres
