---
- name: INSTALL PHPPGADMIN TASK
  apt:
    name: phppgadmin
    state: present
    update_cache: yes

- name: COPY PHPPGADMIN CONFIG FILE TASK
  copy:
    src: "{{ item }}"
    dest: /etc/phppgadmin/
  with_items: 
    - ./files/config.inc.php

- name: COPY PHPPGADMIN APACHE CONFIG FILE TASK
  copy:
    src: "{{ item }}"
    dest: /etc/apache2/sites-available/
  with_items: 
    - ./files/phppgadmin.conf

- name: DISABLE DEFAULT APACHE2 SITE TASK
  command: a2dissite 000-default

- name: DISABLE PHPPGADMIN APACHE2 CONFIG TASK
  command: a2disconf phppgadmin

- name: ENABE PHPPGADMIN APACHE2 SITE TASK
  command: a2ensite phppgadmin

- name: RESTART APACHE2 TASK
  systemd:
    name: apache2
    state: restarted
